package academy

import "time"

// CreateAcademyInput represents the request payload used to create a new academy.
type CreateAcademyInput struct {
	Name       string `json:"name"`        // Unique name representing the academy (cannot be blank)
	Address    string `json:"address"`     // Full physical location/address of the academy
}

// AcademyResponse represents the detailed database response for a single academy record.
type AcademyResponse struct {
	ID         string    `json:"id"`          // Unique UUID identifier generated by the database
	Name       string    `json:"name"`        // Name of the academy
	DistrictID int       `json:"district_id"` // ID of the parent district
	StateID    int    `json:"state_id"`    // State ID retrieved via database JOIN
	Address    string    `json:"address"`     // Address details
	IsActive   bool      `json:"is_active"`   // Activation status of the academy (default: true)
	CreatedAt  time.Time `json:"created_at"`  // Date and time when the record was created
	UpdatedAt  time.Time `json:"updated_at"`  // Date and time of the last record update
}

// GetAcademiesQuery represents the request query options parsed from the HTTP request.
type GetAcademiesQuery struct {
	Page       int    `json:"page"`        // Current page number (must be >= 1)
	Limit      int    `json:"limit"`       // Items per page (use 0/all to retrieve everything)
	Search     string `json:"search"`      // Optional search string matching name or address
	StateID    int    `json:"state_id"`    // Optional filter restrict by state ID
	DistrictID int    `json:"district_id"` // Optional filter restrict by district ID
	SortBy     string `json:"sort_by"`     // Dynamic sort column name (defaults to "name")
	OrderBy    string `json:"order_by"`    // Sort ordering direction ("ASC" or "DESC")
}

// PaginatedAcademies contains a list of Academy objects along with standard metadata pagination metrics.
type PaginatedAcademies struct {
	Items       []AcademyResponse `json:"items"`        // Slice of retrieved academy records
	Page        int       `json:"page"`         // Current page number
	Limit       int       `json:"limit"`        // Limit setting applied
	Total       int       `json:"total"`        // Total count matching filters
	TotalPages  int       `json:"total_pages"`  // Total page count calculated dynamically
	HasNext     bool      `json:"has_next"`     // Boolean indicating if next page is available
	HasPrevious bool      `json:"has_previous"` // Boolean indicating if previous page is available
}

type CreateAcademyBuildingInput struct {
	BuildingName string `json:"building_name"`
}

type AcademyBuildingResponse struct {
	ID           int64  `json:"id"`
	AcademyID    string `json:"academy_id"`
	BuildingName string `json:"building_name"`
	IsActive     bool   `json:"is_active"`
}

type AddAcademyBuildingDisciplineInput struct {
	DisciplineID int `json:"discipline_id"`
}

type AcademyBuildingDisciplineResponse struct {
	AcademyBuildingID int `json:"academy_building_id"`
	DisciplineID      int `json:"discipline_id"`
}

type AddAcademyBuildingEventInput struct {
	ShootingEventID int `json:"shooting_event_id"`
}

type AcademyBuildingEventResponse struct {
	AcademyBuildingID int64 `json:"academy_building_id"`
	ShootingEventID   int   `json:"shooting_event_id"`
}

type BuildingDiscipline struct {
	ID          int    `json:"id"`
	Code        string `json:"code"`
	DisplayName string `json:"display_name"`
}

type BuildingEvent struct {
	ID          int    `json:"id"`
	Code        string `json:"code"`
	DisplayName string `json:"display_name"`
}

type AcademyBuilding struct {
	ID           int64                `json:"id"`
	AcademyID    string               `json:"academy_id"`
	BuildingName string               `json:"building_name"`
	IsActive     bool                 `json:"is_active"`
	Disciplines  []BuildingDiscipline `json:"disciplines"`
	Events       []BuildingEvent      `json:"events"`
}

type AddAcademyBuildingLaneInput struct {
	LaneName string `json:"lane_name" validate:"required,max=50"`
}

type AcademyBuildingLaneResponse struct {
	ID                 int64  `json:"id"`
	AcademyBuildingID  int64  `json:"academy_building_id"`
	LaneName           string `json:"lane_name"`
	IsUnderMaintenance bool   `json:"is_under_maintenance"`
	IsOccupied         bool   `json:"is_occupied"`
}

type AvailableLaneResponse struct {
	ID       int64  `json:"id"`
	LaneName string `json:"lane_name"`
}